### Importing required libraries

In [1]:
import xlrd
import pandas as pd

### Input variables

In [2]:
### Year should be in form a matrix, even if a single value, please put it inside a matrix
year = [2011, 2012]
### filename should be with the path, if it is local file, no need of path
### IMPORTANT [FILE SHOULD BE IN xls format only], this script will not work with xlsx format
filename_with_path = 'myb3-2015-ch.xls'
### SHEET NAME, in some examples it was 'Table1' and in others it was 'Table 1', hence this variable
sheet_name = 'Table1'
### UNIT name default is mentioend as 'metric_tons'
unit_name = 'metric_tons'
### THIS is the row number from where the original table starts, in china example the values start at 8, hence this value is 7
row_number_start_data = 7
### Below is for filename
country_name = 'China'
### In some instances the unit column number is 'B', and in some sheets this column was 'D', if the column is 'B', the value should be 1
unit_column_number = 1

### Function to flatten to dataframe and save it in csv required format

In [3]:
def get_dataframe(year, filename_with_path, sheet_name, unit_name, row_number_start_data, country_name, unit_column_number):

    global c_unit_name, b_unit_name
    book = xlrd.open_workbook(filename_with_path, formatting_info=True)

    sheet = book.sheet_by_name(sheet_name)
    num_rows = sheet.nrows
    values_row = (sheet.row_values(5))[3:]
    year_row_list = []

    commdity_names  = []

    unit_name_list = []

    for i in range(row_number_start_data,num_rows):
        cell = sheet.cell(i,0)
        unit_cell = sheet.cell(i,unit_column_number)
        fmt = book.xf_list[cell.xf_index]
        if fmt.alignment.indent_level == 0:
            a = cell.value
            if (':' not in cell.value) & (len(a) > 1) & ('white' not in cell.value) & ('includes' not in cell.value) & ('Commodity' not in cell.value) & ('Estimated' not in cell.value) & ('available' not in cell.value) & ('Table' not in cell.value) & ('Reported' not in cell.value) & ('Includes' not in cell.value) & ('addition' not in cell.value) & ('Ditto' not in cell.value) & ('Commodity' not in cell.value) & ('Continued' not in cell.value) & ('footnotes' not in cell.value) & ('unless' not in cell.value):
                if not cell.value.isupper():
                    # print('Intend:0: ', cell.value)
                    commdity_names.append(cell.value)
                    if len(unit_cell.value) > 1:
                        if unit_cell.value != 'do.':
                            print('Intend:0: ', cell.value, unit_cell.value, sheet.row_values(i)[3:])
                            unit_name_list.append(unit_cell.value)
                            a_unit_name = unit_cell.value
                            year_row_list.append(sheet.row_values(i)[3:])
                        elif unit_cell.value == 'do.':
                            print('Intend:0: ', cell.value, '\t Unit name: ', a_unit_name, sheet.row_values(i)[3:])
                            unit_name_list.append(a_unit_name)
                            year_row_list.append(sheet.row_values(i)[3:])
                    else:
                        print('Intend:0: ', cell.value, '\t Unit name: ', unit_name, sheet.row_values(i)[3:])
                        unit_name_list.append(unit_name)
                        year_row_list.append(sheet.row_values(i)[3:])

        if fmt.alignment.indent_level == 1:
            if (':' not in cell.value):
                # print('Intend:1: ', a + cell.value)
                commdity_names.append(a + cell.value)
                if len(unit_cell.value) > 1:
                    if unit_cell.value != 'do.':
                        print('Intend:1: ', a + cell.value, '\t Unit name: ', unit_cell.value, sheet.row_values(i)[3:])
                        unit_name_list.append(unit_cell.value)
                        b_unit_name = unit_cell.value
                        year_row_list.append(sheet.row_values(i)[3:])
                    elif unit_cell.value == 'do.':
                        print('Intend:1: ', a + cell.value, '\t Unit name: ', b_unit_name, sheet.row_values(i)[3:])
                        unit_name_list.append(b_unit_name)
                        year_row_list.append(sheet.row_values(i)[3:])
                else:
                    print('Intend:1: ', a + cell.value, '\t Unit name: ', unit_name, sheet.row_values(i)[3:])
                    unit_name_list.append(unit_name)
                    year_row_list.append(sheet.row_values(i)[3:])
            else:
                b = cell.value
        if fmt.alignment.indent_level == 2:
            if ('which' not in cell.value) & (':' not in cell.value) & ('Total' not in cell.value):
                # print('Intend:2: ',a + b + cell.value)
                commdity_names.append(a+ b +cell.value)
                if len(unit_cell.value) > 1:
                    if unit_cell.value != 'do.':
                        print('Intend:2 cell value: ',a + b + cell.value, '\t Unit name: ', unit_cell.value, sheet.row_values(i)[3:])
                        unit_name_list.append(unit_cell.value)
                        year_row_list.append(sheet.row_values(i)[3:])
                        # globals(c_unit_name)
                        c_unit_name = unit_cell.value
                    elif unit_cell.value == 'do.':
                        print('Intend:2: ',a + b + cell.value, '\t Unit name: ', b_unit_name, sheet.row_values(i)[3:])
                        unit_name_list.append(b_unit_name)
                        year_row_list.append(sheet.row_values(i)[3:])

                else:
                    print('Intend:2: ',a + b + cell.value, '\t Unit name: ', unit_name, sheet.row_values(i)[3:])
                    unit_name_list.append(unit_name)
                    year_row_list.append(sheet.row_values(i)[3:])

            if (':' in cell.value):
                c = cell.value
        if fmt.alignment.indent_level == 3:
            if ('Total' not in cell.value):
                # print('Intend 3: ', a + b + c + cell.value)
                commdity_names.append(a + b + c + cell.value)
                if len(unit_cell.value) > 1:
                    if unit_cell.value != 'do.':
                        print('Intend 3: ', a + b + c + cell.value, '\t Unit name: ', unit_cell.value, sheet.row_values(i)[3:])
                        unit_name_list.append(unit_cell.value)
                        year_row_list.append(sheet.row_values(i)[3:])
                        # globals(c_unit_name)
                        c_unit_name = unit_cell.value
                    elif unit_cell.value == 'do.':
                        # if b_unit_name:
                        #     print('Intend 3: ', a + b + c + cell.value, '\t Unit name: ', b_unit_name, sheet.row_values(i)[3:])
                        #     unit_name_list.append(b_unit_name)
                        #     year_row_list.append(sheet.row_values(i)[3:])
                        # else:
                        try:
                            print('Intend 3: ', a + b + c + cell.value, '\t Unit name: ', b_unit_name,
                                  sheet.row_values(i)[3:])
                            unit_name_list.append(b_unit_name)
                            year_row_list.append(sheet.row_values(i)[3:])

                        except NameError:
                            print("well, it WASN'T defined after all!")
                            print('Intend 3: ', a + b + c + cell.value, '\t Unit name: ', c_unit_name, sheet.row_values(i)[3:])
                            unit_name_list.append(c_unit_name)
                            year_row_list.append(sheet.row_values(i)[3:])
                else:
                    print('Intend 3: ', a + b + c + cell.value, '\t Unit name: ', unit_name, sheet.row_values(i)[3:])
                    unit_name_list.append(unit_name)
                    year_row_list.append(sheet.row_values(i)[3:])

    df = pd.DataFrame()
    df['commdity_names'] = pd.Series(commdity_names)
    df['unit_names'] = pd.Series(unit_name_list)

    index_year_input = []
    year_list_to_df = []
    for index,i in enumerate(values_row):
        if i in year:
            index_year_input.append(index)
    for k in index_year_input:
        temp_list = []
        for j in year_row_list:
            temp_list.append(j[k])
        year_list_to_df.append(temp_list)

    print(len(year_list_to_df))
    for index, m in enumerate(year):
        df[m] = pd.Series(year_list_to_df[index])

    print(len(df))
    if len(year) > 1:
        df.to_csv('{}{}-{}.csv'.format(country_name,
                                      year[0],
                                      year[-1]))
    elif len(year) == 1:
        df.to_csv('{}{}.csv'.format(country_name,
                                    year[0]))


    return df

In [4]:
get_dataframe(year, filename_with_path, sheet_name, unit_name, row_number_start_data, country_name, unit_column_number)

Intend:1:  Aluminum:Bauxite, gross weight 	 Unit name:  thousand metric tons [45000.0, '', 47000.0, '', 50400.0, '', 59200.0, 'r', 65000.0, '', '', '', '', '']
Intend:1:  Aluminum:Alumina 	 Unit name:  thousand metric tons [34100.0, '', 37700.0, '', 47000.0, 'r', 51300.0, 'r', 59000.0, '', '', '', '', '']
Intend:2:  Aluminum:Metal:Primary 	 Unit name:  thousand metric tons [20100.0, 'r', 23500.0, 'r', 26500.0, 'r', 28300.0, 'r', 31400.0, '', '', '', '', '']
Intend:2:  Aluminum:Metal:Secondary 	 Unit name:  thousand metric tons [4400.0, 'r', 4830.0, 'r', 5270.0, 'r', 5650.0, 'r', 6000.0, '', '', '', '', '']
Intend:1:  Antimony:Mine, Sb content 	 Unit name:  metric_tons [150000.0, '', 136000.0, '', 121000.0, '', 123000.0, 'r', 111000.0, '', '', '', '', '']
Intend:1:  Antimony:Metal 	 Unit name:  metric_tons [200000.0, '', 240000.0, '', 263000.0, 'r', 235000.0, 'r', 201000.0, '', '', '', '', '']
Intend:1:  Bismuth:Mine output, Bi content 	 Unit name:  metric_tons [1540.0, 'r', 2500.0, 'r', 1400.0, 'r', 1500.0, 'r', 1400.0, '', '', '', '', '']
Intend:1:  Bismuth:Metal 	 Unit name:  metric_tons [15000.0, '', 15000.0, '', 15500.0, '', 15900.0, 'r', 15000.0, '', '', '', '', '']
Intend:0:  Cadmium, smelter 	 Unit name:  metric_tons [6670.0, '', 7270.0, '', 7500.0, 'r', 8200.0, 'r', 7600.0, '', '', '', '', '']
Intend:0:  Chromite, gross weight thousand metric tons [211.0, 'r', 123.0, 'r', 105.0, 'r', 24.0, 'r', 20.0, '', '', '', '', '']
Intend:1:  Cobalt:Mine output, Co content 	 Unit name:  metric_tons [1500.0, 'r', 1500.0, 'r', 1500.0, 'r', 1600.0, 'r', 1600.0, '', '', '', '', '']
Intend:1:  Cobalt:Refined  	 Unit name:  metric_tons [35000.0, '', 29800.0, '', 36100.0, '', 39300.0, '', 48700.0, '', '', '', '', '']
Intend:1:  Copper:Mine output, Cu content 	 Unit name:  thousand metric tons [1270.0, '', 1550.0, 'r', 1680.0, 'r', 1740.0, 'r', 1670.0, '', '', '', '', '']
Intend:2:  Copper:Metal:Smelter, primary 	 Unit name:  thousand metric tons [3030.0, '', 3600.0, '', 4230.0, 'r', 5170.0, 'r', 5500.0, '', '', '', '', '']
Intend 3:  Copper:Metal:Refined:Primary 	 Unit name:  thousand metric tons [3390.0, '', 3930.0, '', 4690.0, 'r', 4820.0, '', 4960.0, '', '', '', '', '']
Intend 3:  Copper:Metal:Refined:Secondary 	 Unit name:  thousand metric tons [1850.0, '', 1950.0, '', 1980.0, 'r', 2830.0, 'r', 3000.0, '', '', '', '', '']
Intend:0:  Germanium 	 Unit name:  metric_tons [110.0, '', 105.0, '', 110.0, '', 120.0, 'r', 127.0, '', '', '', '', '']
Intend:0:  Gold, mine output, Au content 	 Unit name:  metric_tons [362.0, '', 403.0, '', 428.0, '', 451.0, 'r', 450.0, '', '', '', '', '']
Intend:0:  Indium, primary and secondary 	 Unit name:  metric_tons [380.0, '', 405.0, '', 430.0, '', 460.0, '', 350.0, '', '', '', '', '']
Intend:2 cell value:  Iron and steel:Iron ore:Crude ore, gross weight 	 Unit name:  thousand metric tons [1330000.0, '', 1330000.0, '', 1450000.0, '', 1510000.0, '', 1380000.0, '', '', '', '', '']
Intend:2:  Iron and steel:Iron ore:Usable ore, gross weight 	 Unit name:  thousand metric tons [442000.0, '', 420000.0, '', 417000.0, '', 410000.0, '', 375000.0, '', '', '', '', '']
Intend:2:  Iron and steel:Iron ore:Usable ore, Fe content 	 Unit name:  thousand metric tons [274000.0, '', 261000.0, '', 259000.0, '', 254000.0, '', 232000.0, '', '', '', '', '']
Intend:1:  Iron and steel:Pig iron4 	 Unit name:  thousand metric tons [640510.0, '', 663500.0, '', 708970.0, '', 713740.0, '', 691410.0, '', '', '', '', '']
Intend:1:  Iron and steel:Ferroalloys 	 Unit name:  thousand metric tons [28400.0, '', 31300.0, '', 37700.0, '', 37900.0, 'r', 36000.0, '', '', '', '', '']
Intend:2:  Iron and steel:Steel:4Crude 	 Unit name:  thousand metric tons [685280.0, '', 723880.0, '', 779040.0, '', 822300.0, '', 803820.0, '', '', '', '', '']
Intend:2:  Iron and steel:Steel:4Rolled 	 Unit name:  thousand metric tons [886190.0, '', 955780.0, '', 1067620.0, '', 1125130.0, '', 1123500.0, '', '', '', '', '']
Intend:1:  Lead:Mine output, Pb content 	 Unit name:  thousand metric tons [2400.0, '', 2610.0, '', 2700.0, 'r', 2610.0, 'r', 2340.0, '', '', '', '', '']
Intend:2:  Lead:Metal:Smelter, primary 	 Unit name:  thousand metric tons [3110.0, '', 3120.0, '', 3200.0, '', 3050.0, '', 3050.0, '', '', '', '', '']
Intend 3:  Lead:Metal:Refined:Primary 	 Unit name:  thousand metric tons [3200.0, '', 3220.0, '', 3440.0, 'r', 3210.0, 'r', 3080.0, '', '', '', '', '']
Intend 3:  Lead:Metal:Refined:Secondary 	 Unit name:  thousand metric tons [1400.0, '', 1370.0, '', 1500.0, '', 1530.0, 'r', 1620.0, '', '', '', '', '']
Intend:0:  Magnesium, metal 	 Unit name:  metric_tons [675000.0, '', 698000.0, '', 770000.0, '', 874000.0, '', 852000.0, '', '', '', '', '']
Intend:2 cell value:  Manganese:Ore:Gross weight 	 Unit name:  thousand metric tons [20000.0, '', 20000.0, '', 17500.0, '', 15500.0, '', 13000.0, '', '', '', '', '']
Intend:2:  Manganese:Ore:Mn content 	 Unit name:  thousand metric tons [3800.0, 'r', 3800.0, 'r', 3150.0, 'r', 2600.0, 'r', 2100.0, '', '', '', '', '']
Intend:1:  Manganese:Metal 	 Unit name:  thousand metric tons [1480.0, '', 1110.0, 'r', 1050.0, 'r', 1060.0, 'r', 930.0, '', '', '', '', '']
Intend:0:  Mercury, mine output, Hg content 	 Unit name:  metric_tons [1500.0, '', 1350.0, '', 1820.0, 'r', 2260.0, 'r', 2800.0, '', '', '', '', '']
Intend:0:  Molybdenum, mine output, Mo content 	 Unit name:  metric_tons [103000.0, '', 120000.0, '', 122000.0, 'r', 129000.0, 'r', 135000.0, '', '', '', '', '']
Intend:1:  Nickel:Mine output, Ni content 	 Unit name:  metric_tons [90000.0, '', 93300.0, '', 93300.0, '', 98400.0, '', 92900.0, '', '', '', '', '']
Intend:1:  Nickel:Matte 	 Unit name:  metric_tons [166000.0, '', 153000.0, '', 157000.0, 'r', 160000.0, 'r', 160000.0, '', '', '', '', '']
Intend:1:  Nickel:Smelter 	 Unit name:  metric_tons [175000.0, '', 197000.0, '', 227000.0, 'r', 247000.0, 'r', 232000.0, '', '', '', '', '']
Intend:1:  Niobium and tantalum, mine output:Nb2O5 content 	 Unit name:  metric_tons [20.0, 'r', 21.0, 'r', 22.0, 'r', 28.0, 'r', 43.0, '', '', '', '', '']
Intend:1:  Niobium and tantalum, mine output:Ta2O5 content 	 Unit name:  metric_tons [53.0, 'r', 55.0, 'r', 58.0, 'r', 75.0, 'r', 116.0, '', '', '', '', '']
Intend:0:  Palladium, mine output, Pd content kilograms [850.0, '', 750.0, '', 850.0, '', 850.0, '', 1200.0, '', '', '', '', '']
Intend:0:  Platinum, mine output, Pt content 	 Unit name:  kilograms [1600.0, '', 1400.0, '', 1600.0, '', 1600.0, '', 2300.0, '', '', '', '', '']
Intend:0:  Rhenium, Re content in NH4ReO45  	 Unit name:  kilograms [2100.0, '', 2200.0, '', 2300.0, '', 2350.0, '', 2500.0, '', '', '', '', '']
Intend:0:  Silicon, metal thousand metric tons [1350.0, '', 1130.0, '', 1450.0, 'r', 1710.0, 'r', 1950.0, '', '', '', '', '']
Intend:0:  Silver, mine output, Ag content 	 Unit name:  metric_tons [3230.0, 'r', 3640.0, 'r', 3900.0, 'r', 3670.0, 'r', 3390.0, '', '', '', '', '']
Intend:1:  Tin:Mine output, Sn content 	 Unit name:  metric_tons [94100.0, 'r', 91000.0, 'r', 10100.0, 'r', 10200.0, '', 11000.0, '', '', '', '', '']
Intend:1:  Tin:Metal 	 Unit name:  metric_tons [156000.0, '', 148000.0, '', 159000.0, '', 187000.0, '', 167000.0, '', '', '', '', '']
Intend:1:  Titanium:Ilmenite, TiO2 equivalent  	 Unit name:  metric_tons [1330000.0, 'r', 1800000.0, 'r', 1910000.0, 'r', 1900000.0, 'r', 2100000.0, '', '', '', '', '']
Intend:1:  Titanium:Sponge 	 Unit name:  metric_tons [68000.0, '', 82000.0, '', 82600.0, 'r', 68200.0, 'r', 54800.0, '', '', '', '', '']
Intend:0:  Tungsten, mine output, W content 	 Unit name:  metric_tons [61800.0, '', 64400.0, '', 71100.0, '', 71000.0, '', 73000.0, '', '', '', '', '']
Intend:0:  Vanadium, V2O5 in vanadiferous slag product 	 Unit name:  metric_tons [65000.0, '', 71000.0, '', 80000.0, '', 85000.0, 'r', 80000.0, '', '', '', '', '']
Intend:1:  Zinc:Mine output, Zn content 	 Unit name:  thousand metric tons [4050.0, '', 4860.0, 'r', 5190.0, 'r', 5120.0, 'r', 4750.0, '', '', '', '', '']
Intend:2:  Zinc:Refined:Primary 	 Unit name:  thousand metric tons [5040.0, '', 4770.0, '', 5160.0, '', 5610.0, '', 5680.0, '', '', '', '', '']
Intend:2:  Zinc:Refined:Secondary 	 Unit name:  thousand metric tons [173.0, '', 120.0, '', 150.0, '', 170.0, '', 180.0, '', '', '', '', '']
Intend:0:  Asbestos 	 Unit name:  metric_tons [370000.0, 'r', 320000.0, 'r', 280000.0, 'r', 250000.0, 'r', 210000.0, '', '', '', '', '']
Intend:0:  Barite thousand metric tons [5540.0, 'r', 5400.0, 'r', 5260.0, 'r', 5130.0, 'r', 5000.0, '', '', '', '', '']
Intend:0:  Bentonite 	 Unit name:  thousand metric tons [3500.0, '', 4000.0, 'r', 4500.0, 'r', 5000.0, 'r', 5600.0, '', '', '', '', '']
Intend:0:  Boron, mine output, B2O3 equivalent 	 Unit name:  metric_tons [150000.0, '', 132000.0, 'r', 114000.0, 'r', 97000.0, 'r', 90000.0, '', '', '', '', '']
Intend:0:  Bromine 	 Unit name:  metric_tons [235000.0, 'r', 160000.0, 'r', 110000.0, '', 75500.0, 'r', 60000.0, '', '', '', '', '']
Intend:0:  Celestite 	 Unit name:  metric_tons [116000.0, '', 96000.0, '', 76000.0, '', 50600.0, '', 50000.0, '', '', '', '', '']
Intend:0:  Cement, hydraulic4 million metric tons [2099.0, '', 2210.0, '', 2411.0, '', 2492.0, '', 2359.0, '', '', '', '', '']
Intend:0:  Clays, kaolin thousand metric tons [3200.0, '', 3300.0, '', 3300.0, '', 3200.0, '', 3200.0, '', '', '', '', '']
Intend:0:  Diatomite 	 Unit name:  metric_tons [187000.0, 'r', 250000.0, 'r', 310000.0, 'r', 379000.0, 'r', 350000.0, '', '', '', '', '']
Intend:0:  Dolomite thousand metric tons [6320.0, 'r', 7300.0, 'r', 8330.0, 'r', 9520.0, 'r', 10600.0, '', '', '', '', '']
Intend:0:  Feldspar 	 Unit name:  thousand metric tons [3180.0, 'r', 3350.0, 'r', 3500.0, 'r', 3670.0, 'r', 3500.0, '', '', '', '', '']
Intend:0:  Fluorspar 	 Unit name:  thousand metric tons [5660.0, 'r', 5200.0, 'r', 4800.0, 'r', 4310.0, 'r', 3820.0, '', '', '', '', '']
Intend:1:  Graphite:Aphanitic 	 Unit name:  metric_tons [500000.0, '', 150000.0, '', 140000.0, '', 250000.0, '', 200000.0, '', '', '', '', '']
Intend:1:  Graphite:Flake 	 Unit name:  metric_tons [700000.0, '', 650000.0, '', 700000.0, '', 650000.0, '', 660000.0, '', '', '', '', '']
Intend:1:  Gypsum:Natural 	 Unit name:  thousand metric tons [35600.0, 'r', 35000.0, 'r', 28000.0, 'r', 20000.0, 'r', 20000.0, '', '', '', '', '']
Intend:1:  Gypsum:Byproduct 	 Unit name:  thousand metric tons [169000.0, '', 172000.0, '', 184000.0, '', 192000.0, '', 200000.0, '', '', '', '', '']
Intend:0:  Lime 	 Unit name:  thousand metric tons [186000.0, 'r', 200000.0, 'r', 220000.0, 'r', 230000.0, 'r', 220000.0, '', '', '', '', '']
Intend:1:  Lithium:Mine output, Li content 	 Unit name:  metric_tons [2120.0, 'r', 1900.0, 'r', 2100.0, 'r', 1900.0, 'r', 2000.0, '', '', '', '', '']
Intend:1:  Lithium:Lithium carbonate 	 Unit name:  metric_tons [30000.0, '', 35000.0, '', 38000.0, '', 41600.0, '', 42000.0, '', '', '', '', '']
Intend:1:  Lithium:Lithium hydroxide 	 Unit name:  metric_tons [14000.0, '', 18000.0, '', 22000.0, '', 21000.0, '', 22000.0, '', '', '', '', '']
Intend:1:  Lithium:Lithium metal 	 Unit name:  metric_tons [1700.0, '', 2000.0, '', 2300.0, '', 2650.0, '', 2680.0, '', '', '', '', '']
Intend:0:  Magnesite thousand metric tons [19000.0, '', 16000.0, '', 17000.0, '', 16000.0, '', 17000.0, '', '', '', '', '']
Intend:0:  Mica, natural 	 Unit name:  metric_tons [71800.0, 'r', 56000.0, 'r', 41000.0, 'r', 25600.0, 'r', 25000.0, '', '', '', '', '']
Intend:0:  Nitrogen, N content of ammonia4 thousand metric tons [43250.0, '', 45520.0, '', 48326.0, '', 45642.0, '', 49706.0, '', '', '', '', '']
Intend:0:  Phosphate rock, P2O5 equivalent 	 Unit name:  thousand metric tons [24000.0, '', 28500.0, '', 33500.0, '', 36000.0, '', 42600.0, '', '', '', '', '']
Intend:0:  Potash, marketable, K2O equivalent 	 Unit name:  thousand metric tons [3800.0, '', 3770.0, '', 5300.0, '', 6110.0, '', 5710.0, '', '', '', '', '']
Intend:0:  Rare earths, rare-earth oxide equivalent 	 Unit name:  metric_tons [105000.0, '', 100000.0, '', 95000.0, '', 105000.0, '', 105000.0, '', '', '', '', '']
Intend:0:  Salt4 thousand metric tons [67420.0, '', 69120.0, '', 73676.0, '', 70497.0, '', 66655.0, '', '', '', '', '']
Intend:1:  Sodium compounds:Caustic soda4 	 Unit name:  thousand metric tons [24740.0, '', 26970.0, '', 29270.0, '', 30640.0, '', 30210.0, '', '', '', '', '']
Intend:1:  Sodium compounds:Mirabilite 	 Unit name:  thousand metric tons [8540.0, 'r', 7400.0, 'r', 6500.0, 'r', 5750.0, 'r', 5700.0, '', '', '', '', '']
Intend:1:  Sodium compounds:Soda ash, natural and synthetic4 	 Unit name:  thousand metric tons [22940.0, '', 24010.0, '', 24320.0, '', 25260.0, '', 25920.0, '', '', '', '', '']
Intend:2:  Sulfur, S content:eByproduct, domestic:Nonferrous, metallurgy 	 Unit name:  thousand metric tons [3270.0, '', 3370.0, '', 3560.0, '', 4140.0, '', 3800.0, '', '', '', '', '']
Intend:2:  Sulfur, S content:eByproduct, domestic:Petroleum and coal chemical industry 	 Unit name:  thousand metric tons [4770.0, '', 4910.0, '', 5190.0, '', 6020.0, '', 5530.0, '', '', '', '', '']
Intend:1:  Sulfur, S content:ePyrite 	 Unit name:  thousand metric tons [5660.0, 'r', 5820.0, 'r', 6150.0, 'r', 7140.0, 'r', 6570.0, '', '', '', '', '']
Intend:0:  Talc and related materials 	 Unit name:  thousand metric tons [2140.0, 'r', 2060.0, 'r', 1970.0, 'r', 1870.0, 'r', 1800.0, '', '', '', '', '']
Intend:1:  Coal:Anthracite 	 Unit name:  thousand metric tons [450000.0, '', 470000.0, 'r', 451000.0, 'r', 422000.0, 'r', 401000.0, '', '', '', '', '']
Intend:1:  Coal:Bituminous 	 Unit name:  thousand metric tons [2800000.0, '', 2820000.0, 'r', 3220000.0, 'r', 3190000.0, 'r', 3100000.0, '', '', '', '', '']
Intend:1:  Coal:Lignite 	 Unit name:  thousand metric tons [270000.0, '', 371000.0, 'r', 300000.0, 'r', 272000.0, 'r', 252000.0, '', '', '', '', '']
Intend:0:  Coke, all types4 	 Unit name:  thousand metric tons [432710.0, '', 447790.0, '', 481794.0, '', 479809.0, '', 448225.0, '', '', '', '', '']
Intend:0:  Gas, natural, gross billion cubic meters [102.0, '', 107.0, '', 121.0, '', 130.0, '', 135.0, '', '', '', '', '']
Intend:1:  Petroleum:Crude, including crude from oil shale 	 Unit name:  million 42-gallon barrels [1480.0, '', 1510.0, '', 1520.0, '', 1530.0, '', 1550.0, '', '', '', '', '']
Intend:1:  Petroleum:Refinery products 	 Unit name:  million 42-gallon barrels [3170.0, 'r', 3360.0, 'r', 3500.0, 'r', 3710.0, 'r', 3900.0, '', '', '', '', '']
Intend:0:  Uranium, mine output, U content 	 Unit name:  metric_tons [885.0, 'r', 1500.0, 'r', 1450.0, 'r', 1500.0, 'r', 1620.0, '', '', '', '', '']
2
98

,commdity_names,unit_names,2011,2012
0,"Aluminum:Bauxite, gross weight",thousand metric tons,45000.0,47000.0
1,Aluminum:Alumina,thousand metric tons,34100.0,37700.0
2,Aluminum:Metal:Primary,thousand metric tons,20100.0,23500.0
3,Aluminum:Metal:Secondary,thousand metric tons,4400.0,4830.0
4,"Antimony:Mine, Sb content",metric_tons,150000.0,136000.0
...,...,...,...,...
93,"Coke, all types4",thousand metric tons,432710.0,447790.0
94,"Gas, natural, gross",billion cubic meters,102.0,107.0
95,"Petroleum:Crude, including crude from oil shale",million 42-gallon barrels,1480.0,1510.0
96,Petroleum:Refinery products,million 42-gallon barrels,3170.0,3360.0
97,"Uranium, mine output, U content",metric_tons,885.0,1500.0